sqlplus sys/Thedev1108@localhost:1521/XE as sysdba

show pdbs
select tablespace_name, con_id from cdb_tablespaces;


CREATE TABLESPACE my_tablespace DATAFILE 'my_tablespace.dat' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE USER ldt IDENTIFIED BY Thedev1108
DEFAULT TABLESPACE my_tablespace
TEMPORARY TABLESPACE temp;

CREATE USER ldt IDENTIFIED BY Thedev1108
DEFAULT TABLESPACE my_tablespace
TEMPORARY TABLESPACE temp;

GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM TO ldt;

ALTER USER ldt QUOTA UNLIMITED ON my_tablespace;


ALTER SESSION SET CURRENT_SCHEMA=system;

CREATE TABLE USERTABLE (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255),
    email VARCHAR2(255),
    password VARCHAR2(255),
    PRIMARY KEY (id)
) TABLESPACE my_tablespace;
INSERT INTO USERTABLE (name, email, password) VALUES ('John Doe', 'john.doe@example.com', 'password123');
INSERT INTO USERTABLE (name, email, password) VALUES ('Jane Smith', 'jane.smith@example.com', 'password456');


CREATE TABLE BOARDTABLE (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255),
    userId NUMBER,
    PRIMARY KEY (id),
    FOREIGN KEY (userId) REFERENCES USERTABLE(id)
) TABLESPACE my_tablespace;
INSERT INTO BOARDTABLE (name, userId) VALUES ('Project A', 1);
INSERT INTO BOARDTABLE (name, userId) VALUES ('Project B', 2);


CREATE TABLE TASKCOLUMNTABLE (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255),
    boardId NUMBER,
    userId NUMBER,
    PRIMARY KEY (id),
    FOREIGN KEY (boardId) REFERENCES BOARDTABLE(id),
    FOREIGN KEY (userId) REFERENCES USERTABLE(id)
) TABLESPACE my_tablespace;
INSERT INTO TASKCOLUMNTABLE (name, boardId, userId) VALUES ('To Do', 1, 1);
INSERT INTO TASKCOLUMNTABLE (name, boardId, userId) VALUES ('In Progress', 1, 1);
INSERT INTO TASKCOLUMNTABLE (name, boardId, userId) VALUES ('Done', 2, 2);


CREATE TABLE TASKTABLE (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255),
    description VARCHAR2(2000),
    taskColumnId NUMBER,
    userId NUMBER,
    PRIMARY KEY (id),
    FOREIGN KEY (taskColumnId) REFERENCES TASKCOLUMNTABLE(id),
    FOREIGN KEY (userId) REFERENCES USERTABLE(id)
) TABLESPACE my_tablespace;
INSERT INTO TASKTABLE (name, description, taskColumnId, userId) VALUES ('Task 1', 'Description for Task 1', 1, 1);
INSERT INTO TASKTABLE (name, description, taskColumnId, userId) VALUES ('Task 2', 'Description for Task 2', 2, 1);
INSERT INTO TASKTABLE (name, description, taskColumnId, userId) VALUES ('Task 3', 'Description for Task 3', 3, 2);


select * from USERTABLE;
select * from BOARDTABLE;
select * from TASKCOLUMNTABLE;
select * from TASKTABLE;
